const Theme = {
  colors: {
    background: "#F9F9F9",
    primary: "#7118E3",
    secondary: "#F45B69",
    white: "#FFFFF",
    gray: "#636363",
    border: "#E5E5E5",
    text: "#252525",
    textSecondary: '#636363',
  },
  spacing: {
    n1: "8px",
    n2: "16px",
    n3: "28px",
    n4: "38px",
  },
  font: {
    h1: {
      fontfamily: "Roboto",
      fontStyle: "normal",
      fontWeight: "500",
      fontSize: "50px",
      lineHeight: "59px",
    },
    h2: {
      fonFamily: "Roboto",
      fontStyle: "normal",
      fontWeight: "500",
      fontSize: "38px",
      lineHeight: "45px",
    },
    h3: {
      fontFamily: "Roboto",
      fontStyle: "normal",
      fontWeight: "normal",
      fontSize: "28px",
      lineHeight: "33px",
    },
    h4: {
      fontFamily: "Roboto",
      fontStyle: "normal",
      fontWeight: "normal",
      fontSize: "21px",
      lineHeight: "25px",
    },
    h5: {
      fontFamily: "Roboto",
      fontStyle: "normal",
      fontWeight: "600",
      fontSize: "12px",
      lineHeight: "14px",
    },
    h5Transparent: {
      fontFamily: "Roboto",
      fontStyle: "normal",
      fontWeight: "600",
      fontSize: "12px",
      lineHeight: "14px",
    },
    p: {
      fontFamily: "Roboto",
      fontStyle: "normal",
      fontWeight: "normal",
      fontSize: "16px",
      lineHeight: "20px",
    },
    small: {
      fontFamily: "Roboto",
      fontStyle: "normal",
      fontWeight: "normal",
      fontSize: "12px",
      lineHeight: "14px",
    },
  },
};
export default Theme